import crypto from "node:crypto"
import { sha256Hex } from "./agent-auth.js"
import { env } from "./env.js"

const ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"

/** Short-lived, human-typeable pairing code (e.g. "K7XQ-4RTP") a technician
 * reads off the CMMP portal and types into Windows Setup at :8765 (the
 * MusicServer.Api "Cloud server URL" / link flow — see
 * backend/README.md). Generated by THIS backend, never by the agent. */
export function generatePairingCode(): string {
  const group = () => Array.from({ length: 4 }, () => ALPHABET[crypto.randomInt(ALPHABET.length)]).join("")
  return `${group()}-${group()}`
}

export function hashPairingCode(code: string): string {
  return sha256Hex(normalizePairingCode(code))
}

export function normalizePairingCode(code: string): string {
  return code.trim().toUpperCase()
}

export function pairingExpiry(): Date {
  return new Date(Date.now() + env.agentPairingCodeTtlMinutes * 60 * 1000)
}
